### ISSUE TITLE
Emby compatibility

### ISSUE THREAD

**Issue by ihardyslide** [s0faking/plugin.video.orfon#1]
Hi,

since Emby is a fork of Kodi, I wanted to ask if this plugin is also somehow usable with Emby?

Thanks & BR

**Comment by s0faking** [comment]
Hi,

as far as i know emby is an alternative to plex etc. so it provides a media server. haven't used it but looking up available plugins i saw that they are writen in c#, kodi addons on the other hand are written in python. so this would be a whole other game ;) also i haven't found any information on emby being a kodi fork, but jellyfin is a fork of emby.  since kodi has inputstream adapative included and uses widevine to decrypt drm protected content i don't think this would be possible with emby. sorry
