### ISSUE TITLE
Livestreams: just SD since July 1st, 2024

### ISSUE THREAD

**Issue by Z-Brox** [s0faking/plugin.video.orfon#11]
Hi,

since July 1st all livestreams are shown with max. 540p. According to ORF support streams from on.orf.at/live need a HDCP-enabled setup to show them in HD. I guess that's not supported in Kodi/LibreELEC?

Btw - thank you for your great work, s0faking.

**Comment by s0faking** [comment]
Hi,

just tested this to be sure on Android and Windows, 720p works there. Did you try to configure Inputstream Adaptive to select the quality? You should see a dialog when opening a stream then, the last two items are 720p with different bitrates. If you enabled the timeshift option in the Orf ON addon settings the last two items show no resolution but they are indeed 720p (same as non timeshift setting) Got no test setup for LibreElec right now but since it uses the Chrome OS Widevine there shouldn't be a difference. 

I've moved the ORF On code to the original TVthek addon and renamed the addon so you can try to install the most recent version from the official Kodi Repository and remove the plugin.video.orfon addon.

**Comment by Z-Brox** [comment]
Hallo, s0faking,

I've configured Inputstream Adaptive to "Adaptive" (with a max. resolution of 1080p). After reconfiguring it to ask for the quality I can choose from different quality options as you explained (see attached photo). When I choose one of the last two items audio is played back but no video is shown.
![IMG_20240704_115145](https://github.com/s0faking/plugin.video.orfon/assets/22732856/ad4fbe1f-4d52-4632-b636-4cd519d55a73)

**Comment by s0faking** [comment]
you are right. haven't seen this because i mainly use my nvidia shield which is hdcp compliant. on windows the 720p streams also work, but on my linux devices they don't. 

you can workaround this issue by disabling "use timeshift" in the orf on addon settings. this enables the old livestreams which are still working atm. i have to checkout how to fix the restart though because the "new" restart uses the timeshift streams which are also in place at the orf on website. other than that i'm afraid there is no way to work around this issue because (afaik) most hardware running linux doesn't support hdcp, so let's hope they will keep the old livestreams active :)

**Comment by Z-Brox** [comment]
Vielen Dank, s0faking, haut hin.

Your workaround gives back HD livestreams for now. As you say, let's hope ORF will not stop those old livestreams. I'm still in contact with the ORF Devs (https://dev.orf.at/) so let's see if they can/will do something about that HDCP issue (btw that also gives me max. 540p in webbrowsers when using ORF ON livestreams). Low hopes there though.

Thank's again.

**Comment by Z-Brox** [comment]
For now resolved by workaround suggestion (disabling timeshift).
